# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80c3ef35e5f2aa9e92ad65bb1ea794b72bcf298df7abdc342401ef2c6fb276a5e377f63b2ed87c371b1cba58a05641603202aa130bc15ba368ce2c194102d6c1

test:
  secret_key_base: bc7f6b3a51d28ed6e8ff1efb65d8df9a5f119a4f06a1213f56b2edde90674a43948a02fe73e46e3f978301f638b4f3a4beaa255b4df312ffc1db334a029f0fbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  ninefold_db: testing_ninefold_gen
  ninefold_user: app
  ninefold_pass: epBzIutOsABWuilZl796
  google_analytics_code: 'YOUR CODE HERE'
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>